name: jvs_cloud
description: "IaC & Cloud Management Application - A comprehensive Flutter app for Infrastructure as Code and cloud services management"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  
  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2
  
  # Networking
  dio: ^5.3.2
  connectivity_plus: ^5.0.1
  
  # Secure Storage
  flutter_secure_storage: ^9.0.0
  
  # Routing
  go_router: ^12.1.1
  
  # Internationalization
  flutter_localizations:
    sdk: flutter
  intl: any
  easy_localization: ^3.0.3
  
  # Authentication
  local_auth: ^2.1.6
  crypto: ^3.0.3
  
  # UI Components
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.8
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  lottie: ^2.7.0
  
  # Utilities
  shared_preferences: ^2.2.2
  package_info_plus: ^4.2.0
  device_info_plus: ^9.1.0
  url_launcher: ^6.2.1
  path_provider: ^2.1.1
  dartz: ^0.10.1
  equatable: ^2.0.5
  
  # Code Generation
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  
  # Responsive Design
  responsive_framework: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Linting
  flutter_lints: ^3.0.0
  
  # Code Generation
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  
  # Testing
  bloc_test: ^9.1.5
  mocktail: ^1.0.1
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/translations/
    - assets/code_templates/